apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/sandeshchalise/backend:8
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: mysql.mysql.svc.cluster.local   # 👈 important
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: example
        - name: DB_NAME
          value: mydb

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
